## Remember that the solutions need to be saved int variable provided.

In [1]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [5]:
# 1 point
sol1 = 0
# YOUR CODE HERE
array = np.random.random((10,10))
print(array)
arraymin = array.min()
arraymax = array.max()
print(arraymin,arraymax)


[[0.23341978 0.25737712 0.82906281 0.76574855 0.8649288  0.24057229
  0.74090804 0.82742393 0.88604034 0.91388477]
 [0.08014603 0.49404781 0.85211143 0.63191001 0.29738221 0.44740932
  0.01273149 0.11218738 0.04209145 0.56976652]
 [0.22469342 0.72666684 0.04991639 0.94736801 0.5728833  0.3240593
  0.36782332 0.62860481 0.1138316  0.75195215]
 [0.28194833 0.84548716 0.67592549 0.91326429 0.80588803 0.59575243
  0.43265415 0.05574205 0.62263185 0.07386419]
 [0.81423249 0.70620844 0.53483458 0.77294878 0.77451139 0.30204485
  0.86882564 0.04910769 0.51864161 0.51868187]
 [0.69007171 0.42840919 0.71044387 0.78234735 0.76803458 0.11019415
  0.50393616 0.76505866 0.83670014 0.47523464]
 [0.4943706  0.74873759 0.7484467  0.22310558 0.43900309 0.53296418
  0.83526466 0.9453264  0.37154342 0.61441507]
 [0.89131307 0.04537055 0.82368826 0.9413489  0.51402139 0.38671236
  0.19060278 0.93930541 0.47753018 0.03127123]
 [0.51713326 0.27909779 0.2988008  0.85560039 0.80511002 0.85875414
  0.78316144 

In [6]:
assert array.shape == (10,10)

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [9]:
#1 points
sol2 = 0

# YOUR CODE HERE
array = np.ones((10,10))
print(array)
array[1:-1,1:-1] = 0
print(array)



[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [10]:
assert array.shape == (10,10)
assert array[0].all() == 1
assert array[:,0].all() == 1
assert array[1][1] == 0
assert array[2][2] == 0
assert array[3][3] == 0
assert array[4][4] == 0
assert array[1][2] == 0
assert array[2][3] == 0
assert array[3][4] == 0
assert array[4][5] == 0

**34. How to get all the dates corresponding to the month of July 2016**

In [15]:
#2 points
sol3 = 0

# YOUR CODE HERE
julymonth = (np.arange('2016-07','2016-08',dtype='datetime64[D]'))
print(julymonth)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [16]:
assert julymonth.shape == (31,)
assert type(julymonth[0]) is np.datetime64

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [ ]:
#2 points
sol41 = 0
sol42 = 0
comparisson = 0
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [26]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])

# YOUR CODE 
array[[0,1]] = array[[1,0]]
print(array)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [ ]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
sol6 = 0
# YOUR CODE HERE
raise NotImplementedError()


In [ ]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5